export const enCountries: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
]




export const arCountries: string[] = [
  "آيسلندا",
  "إثيوبيا",
  "أذربيجان",
  "أرمينيا",
  "إريتريا",
  "إسبانيا",
  "أستراليا",
  "إستونيا",
  "إسواتيني",
  "أفغانستان",
  "الأرجنتين",
  "الأردن",
  "الإكوادور",
  "الإمارات العربية المتحدة",
  "ألبانيا",
  "البحرين",
  "البرازيل",
  "البرتغال",
  "البوسنة والهرسك",
  "الجبل الأسود",
  "الجزائر",
  "الدانمارك",
  "السلفادور",
  "السنغال",
  "السودان",
  "السويد",
  "الصومال",
  "الصين",
  "العراق",
  "الغابون",
  "الفاتيكان",
  "الفلبين",
  "الكاميرون",
  "الكونغو",
  "الكويت",
  "المالديف",
  "ألمانيا",
  "المجر",
  "المغرب",
  "المكسيك",
  "المملكة العربية السعودية",
  "المملكة المتحدة",
  "النرويج",
  "النمسا",
  "النيجر",
  "الهند",
  "الولايات المتحدة الأمريكية",
  "اليابان",
  "اليمن",
  "اليونان",
  "أنتيغوا وبربودا",
  "أندورا",
  "إندونيسيا",
  "أنغولا",
  "أوروغواي",
  "أوزبكستان",
  "أوغندا",
  "أوكرانيا",
  "إيران",
  "أيرلندا",
  "إيطاليا",
  "بابوا غينيا الجديدة",
  "باراغواي",
  "باكستان",
  "بالاو",
  "بربادوس",
  "بروناي",
  "بلجيكا",
  "بلغاريا",
  "بليز",
  "بنغلاديش",
  "بنما",
  "بنين",
  "بوتان",
  "بوتسوانا",
  "بوركينا فاسو",
  "بوروندي",
  "بولندا",
  "بوليفيا",
  "بيرو",
  "تايلاند",
  "تايوان",
  "تركمانستان",
  "تركيا",
  "ترينيداد وتوباغو",
  "تشاد",
  "تشيلي",
  "تنزانيا",
  "توجو",
  "توفالو",
  "تونس",
  "تونغا",
  "تيمور الشرقية",
  "جامايكا",
  "جزر البهاما",
  "جزر القمر",
  "جزر سليمان",
  "جزر مارشال",
  "جمهورية أفريقيا الوسطى",
  "جمهورية التشيك",
  "جمهورية الدومينيكان",
  "جنوب أفريقيا",
  "جنوب السودان",
  "جورجيا",
  "جيبوتي",
  "دومينيكا",
  "رواندا",
  "روسيا",
  "روسيا البيضاء",
  "رومانيا",
  "زامبيا",
  "زيمبابوي",
  "ساموا",
  "سان مارينو",
  "سانت فينسنت وجزر غرينادين",
  "سانت كيتس ونيفيس",
  "سانت لوسيا",
  "ساو تومي وبرينسيب",
  "سريلانكا",
  "سلوفاكيا",
  "سلوفينيا",
  "سنغافورة",
  "سوريا",
  "سورينام",
  "سويسرا",
  "سيراليون",
  "سيشل",
  "صربيا",
  "طاجيكستان",
  "عمان",
  "غامبيا",
  "غانا",
  "غرينادا",
  "غواتيمالا",
  "غيانا",
  "غينيا",
  "غينيا الاستوائية",
  "غينيا بيساو",
  "فانواتو",
  "فرنسا",
  "فلسطين",
  "فنزويلا",
  "فنلندا",
  "فيتنام",
  "فيجي",
  "قبرص",
  "قرغيزستان",
  "قطر",
  "كابو فيردي",
  "كازاخستان",
  "كرواتيا",
  "كمبوديا",
  "كندا",
  "كوبا",
  "كوريا الجنوبية",
  "كوريا الشمالية",
  "كوستاريكا",
  "كوسوفو",
  "كولومبيا",
  "كيريباتي",
  "كينيا",
  "لاتفيا",
  "لاوس",
  "لبنان",
  "لوكسمبورغ",
  "ليبيا",
  "ليبيريا",
  "ليتوانيا",
  "ليختنشتاين",
  "ليسوتو",
  "مالاوي",
  "مالطا",
  "مالي",
  "ماليزيا",
  "مدغشقر",
  "مصر",
  "مقدونيا الشمالية",
  "منغوليا",
  "موريتانيا",
  "موريشيوس",
  "موزمبيق",
  "مولدوفا",
  "موناكو",
  "ميانمار",
  "ميكرونيزيا",
  "ناميبيا",
  "ناورو",
  "نيبال",
  "نيجيريا",
  "نيكاراجوا",
  "نيوزيلندا",
  "هايتي",
  "هندوراس",
  "هولندا"
];
